### ISSUE TITLE
1.0.8 not working anymore

### ISSUE THREAD

**Issue by eikaramba** [thosakwe/feathers-seeder#12]
Because of the latest change in the package.json (https://github.com/thosakwe/feathers-seeder/commit/ffdaee95f7e3fee0561bdd1e9136942874b196c0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L5)  i get
```
Error: Cannot find module 'feathers-seeder'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

However when reverting the change(renaming back to .js) it works. I'm using latest nodeJS and intellij via:
`"C:\Program Files\nodejs\node.exe" C:\Users\xxxx\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js -x "node --harmony-async-await" --debug=3001 D:\yyyyyyy\src\index.js `

I think it was just a typo, or there is something special about .jsnpm file format that i wasn't aware of :P

**Comment by thosakwe** [comment]
Yes, it was a typo. Thanks! Going to fix this now.
