### ISSUE TITLE
support faker locale option

### ISSUE THREAD

**Issue by ghost** [thosakwe/feathers-seeder#13]
hi , I want to use custom locale with the faker but it is not pussible to do this . can you add option to change locale in service options level or seeder options level . and when there is no config for locale default back to english ?

thank you

**Comment by thosakwe** [comment]
Sure.

**Comment by bugss** [comment]
var faker = require('faker')
faker.locale = "zh_CN";

above is work for me .  event  did not  run the npm install faker  .

**Comment by thosakwe** [comment]
Guess I can close this?
