### ISSUE TITLE
How to handle several dependent seeds

### ISSUE THREAD

**Issue by jlpellicer** [thosakwe/feathers-seeder#14]
So, I have this scenario (using Postgres/sequelize):
1 insert predefined users
2 insert predefined roles
3 insert predefined users-roles
I'm stuck at the 3rd step, it requires users and roles to exist so that it can insert correctly.

if I use a callback after each template, the seeder tries to execute each following template the same number of times, but if I don't use a callback, then each service is executed asynchronously and it doesn't work because users and/or roles do not exist yet.

How can I do this?

Thanks!

configuration file:
```
module.exports = {
	services: [
		{
			delete: true,
			randomize: false,
			path: 'users',
			templates: [
				{
					user_id: '22d5362c-efdc-11e6-bc64-92361f002671',
					username: 'sss',
					email: 'sss@gmail.com',
					password: '1234'
				}
			],
			callback(user, seed) {
				return seed({
					delete: true,
					randomize: false,
					path: 'roles',
					templates: [
						{
							role_id: '5abec6e0-efda-11e6-bfc0-4979bfeeb47e',
							name: 'admin'
						},
						{
							role_id: '79e7c441-efda-11e6-a9dc-5364a8fb9f30',
							name: 'user'
						},
						{
							role_id: 'a18da632-efdb-11e6-a946-afdca6ae2a45',
							name: 'guest',
							status: 'inactive'
						}
					],
					callback(role, seed) {
						return seed({
							delete: true,
							randomize: false,
							path: 'user_roles',
							templates: [
								{
									user_id: '22d5362c-efdc-11e6-bc64-92361f002671',
									role_id: '5abec6e0-efda-11e6-bfc0-4979bfeeb47e'
								}
							]
						});
					}
				});
			}
		}
	]
};
```

**Comment by thosakwe** [comment]
Hm, wasn't aware of this bug, thanks for pointing it out. Perhaps, try `count: 3` on your `roles` seed? See what happens - hopefully that fixes it. If not, I'll be right on top of it.

Also, you may consider removing your e-mail from the example, as I have no idea what kind of crawlers might be scraping Github.

Thanks for your time! :)

**Comment by jlpellicer** [comment]
Hey, no problem.
But didn't work:

`You may not specify both randomize = false with count`

```
...
callback(user, seed) {
	return seed({
		delete: true,
		randomize: false,
		path: 'roles',
		count: 3,
		templates: [
...
```
Also tried removing `ranomize` and leave `count` but still tries to create one 3 user_roles for each role.

Thanks!

**Comment by thosakwe** [comment]
Hey, did you ever have any luck with this issue, or no?
