### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by codingfriend1** [thosakwe/feathers-seeder#17]
Would you be willing to make the feathers-seeder library MIT license?

**Comment by thosakwe** [comment]
Sure. Can you submit a PR?

**Comment by codingfriend1** [comment]
Wonderful! Thank you. I submitted a pull request, I didn't know who to attribute it to because you didn't mention the owner in the GPL 3.0 license.

**Comment by thosakwe** [comment]
Apologies for the late response. I'll get this published by today or so.

**Comment by thosakwe** [comment]
Now closed. I considered publishing a v1.0.9, but I don't think it's worth pushing to NPM just to change the license.

If it is though, please let me know. Don't want to be a roadblock in the way of you using this package.

**Comment by codingfriend1** [comment]
No worries thanks for the hard work! I will be important, but I can wait if you want to release a few more changes with the update.

**Comment by thosakwe** [comment]
No need to wait. Just published v1.0.9.

**Comment by codingfriend1** [comment]
Thank you! You have a great framework

**Comment by thosakwe** [comment]
Thanks!!!

**Comment by erkkaha** [comment]
package.json still states GPL 3.0, but that should be MIT as well?

**Comment by thosakwe** [comment]
Didn't notice that. Can you send a small PR in? Thanks.

**Comment by erkkaha** [comment]
Changes in #19
