### ISSUE TITLE
enabling https

### ISSUE THREAD

**Issue by harrisrobin** [thosakwe/feathers-seeder#2]
Hi,
great package! Is there an easy way to enable all the URLs to use `https` instead? 

Thanks!

**Comment by thosakwe** [comment]
`feathers-seeder` doesn't run over the network, it runs within your application.

Can you explain what you mean, though?

**Comment by harrisrobin** [comment]
@thosakwe ah I see. It's fakerjs then. I mean that all the URLs of the images you get when doing something like '{{image.city}}' is HTTP and not https. I was simply wondering if they could be switched to https. 

Anyway, this can be closed as I don't think it's possible, thanks! :)

**Comment by thosakwe** [comment]
Ok, cool. I'm writing some updates as we speak.
