### ISSUE TITLE
 ResourceRequest timed out

### ISSUE THREAD

**Issue by musicformellons** [thosakwe/feathers-seeder#23]
When I increase the number of 'users' I seed I get:
```
{ GeneralError: ResourceRequest timed out
    at new GeneralError (/home/usr/api_server/node_modules/feathers-errors/lib/index.js:177:17)
    at /home/usr/api_server/node_modules/feathers-seeder/lib/index.js:45:15
  type: 'FeathersError',
  name: 'GeneralError',
  message: 'ResourceRequest timed out',
  code: 500,
  className: 'general-error',
  data: undefined,
  errors: {} } +0ms
```
With just 10 users it gets through without error, but some more and the error will come.

**Comment by thosakwe** [comment]
You’ll need to send a PR for this. The codebase hasn’t been touched in months, so perhaps you’re using a version of Feathers that introduced breaking changes.

**Comment by musicformellons** [comment]
Yeah, probably. I am on Feathersjs Buzzard. I will write my own script using[ this article.](https://medium.com/@tomaszbak/feathersjs-seeds-with-services-and-async-await-49765c59b7a1)

**Comment by thosakwe** [comment]
It might make more sense to send a PR, so that people can continue to use
feathers-seeder.
