### ISSUE TITLE
question: creating users from predefined data

### ISSUE THREAD

**Issue by jamesholcomb** [thosakwe/feathers-seeder#4]
I have the need to load a set of static user data from a predefined JSON file (they are actual users from an external OAuth provider), rather than generating from a template.

The configuration allows an array of templates that are selected randomly, but that won't guarantee all users are loaded.

What do you recommend?

**Comment by thosakwe** [comment]
Hi, just saw your fork, and I like the idea of a `randomize` flag. Just add some tests, and we can get a PR going.
