### ISSUE TITLE
Import data 1:1 without randomization

### ISSUE THREAD

**Issue by wdmtech** [thosakwe/feathers-seeder#7]
Hey, great project!

Given the following dataset:

```js
export default
  [
      { 'name': '50l bag' },
      { 'name': 'holdall' },
      { 'name': 'bumbag (fannypack)' },
    ]
```

It would be great to be able to import this data 1:1 with the original dataset - no randomization or duplication. Any ideas how I could accomplish this? 

So far I've tried 

```js
import data from './data/items'

let options = {
  path: 'items',
  count: data.length,
  template: [
    ...data
  ]
}

module.exports = options
```

But obvious problems are obvious xD

Cheers @thosakwe!

**Comment by wdmtech** [comment]
Generally I find two myself using two types of seeded data - fake data, and intentional data. Your package certainly covers the fake data usecase, but I can't see how I can make it work with the latter.

**Comment by thosakwe** [comment]
Fortunately, we just patchee this up. When I get home, I'll link to the PR that fixed this.

Thanks to James Holcomb for the commit I merged under a minute ago.

**Comment by wdmtech** [comment]
...I thought I was going mad! I just went back to README.MD and I saw a randomize option... will check the changes!

Thanks @thosakwe and @jamesholcomb

**Comment by thosakwe** [comment]
It hasn't been pushed to NPM yet, but yeah.
